package:
  name: binaryclassifier
  version: "0.1"

source:
  path: .

requirements:
  build:
    - python
    - setuptools ==27.2.0

  run:
    - python

test:
  requires:
    - nose
    - hypothesis >=3.0.0

  files:
    - tests/test_EmulatorMain.py

about:
  home: https://github.com/CSC380Team8/binary-classifier
  license: GPLv3
  license_file: LICENSE
